spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:tcp://localhost/~/db-2;MODE=MYSQL;DATABASE_TO_LOWER=TRUE'
    username: sa
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.jdbc: debug
